<?php

/**
 * LMS Client
 *
 * @package     LMSClient
 * @author      Henri Susanto
 * @copyright   2022 Henri Susanto
 * @license     GPL-2.0-or-later
 *
 * @wordpress-plugin
 * Plugin Name: LMS Client
 * Plugin URI:  https://github.com/susantohenri
 * Description: Fetching LMS Courses
 * Version:     1.0.0
 * Author:      Henri Susanto
 * Author URI:  https://github.com/susantohenri
 * Text Domain: lms-client
 * License:     GPL v2 or later
 * License URI: http://www.gnu.org/licenses/gpl-2.0.txt
 */

define('LMS_CLIENT_CONTENT_GALERY_PAGE_SIZE', 6);
define('LMS_CLIENT_TOKEN', '1a962X0Zw5ZVdxS6a6h2c7iayFN8HWr66o4ncFgom1xRXNAsDE0tfnDjPLGJmqHT');

add_shortcode('lms-client-content-gallery', function () {
    wp_register_style('lms-client-content-gallery', plugin_dir_url(__FILE__) . 'lms-client-content-gallery.css');
    wp_enqueue_style('lms-client-content-gallery');

    wp_register_script('jquery', 'https://code.jquery.com/jquery-3.6.1.slim.min.js');
    wp_enqueue_script('jquery');
    wp_register_script('lms-client-content-gallery', plugin_dir_url(__FILE__) . 'lms-client-content-gallery.js');
    wp_enqueue_script('lms-client-content-gallery');
    wp_localize_script(
        'lms-client-content-gallery',
        'lms_client_content_gallery',
        array(
            'current_page' => 1,
            'content_list_url' => site_url('wp-json/lms-client/v1/contents'),
        )
    );

    return "
    <div class='lms-client'>
        <div class='lms-client-content-gallery'>
        
        </div>
        <div class='lms-client-content-gallery-pagination'>
            <a href='javascript:lms_client_content_gallery_prev()'>&laquo; Previous</a>
            <a href='javascript:lms_client_content_gallery_next()'>Next &raquo;</a>
        </div>
    </div>
    ";
});

add_action('rest_api_init', function () {
    register_rest_route('lms-client/v1', '/contents', array(
        'methods' => 'GET',
        'callback' => function () {
            $response = LMSClientGetContent($_GET['page']);
            return array_map(function ($item) {
                return "
                    <div class='lms-client-content-gallery-item'>
                        <img src='{$item->media->image->raw}'>
                        <div class='lms-client-content-gallery-desc'>{$item->name}</div>
                    </div> 
                ";
            }, $response->results);
        }
    ));
});

function LMSClientGetContent($page)
{
    $pageSize = LMS_CLIENT_CONTENT_GALERY_PAGE_SIZE;
    $token = LMS_CLIENT_TOKEN;

    // Generated by curl-to-PHP: http://incarnate.github.io/curl-to-php/
    $ch = curl_init();
    curl_setopt($ch, CURLOPT_URL, "https://diginusa-english.tenderhub.co/api/courses/v1/courses/?page={$page}&page_size={$pageSize}");
    curl_setopt($ch, CURLOPT_RETURNTRANSFER, 1);
    curl_setopt($ch, CURLOPT_CUSTOMREQUEST, 'GET');
    $headers = array();
    $headers[] = 'Accept: application/json';
    $headers[] = "X-Csrftoken: {$token}";
    curl_setopt($ch, CURLOPT_HTTPHEADER, $headers);
    $result = curl_exec($ch);
    if (curl_errno($ch)) {
        echo curl_error($ch);
        $result = [];
    }
    curl_close($ch);
    return json_decode($result);
}
